{% set data = load_setup_py_data() %}

package:
  name: ciera-template
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy>=1.11.1,<1.16.0

  run:
    - python
    - numpy>=1.11.1,<1.16.0

test:
  imports:
    - YOURPACKAGE

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
